ponytracker/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views


urlpatterns = [
    # django admin
    url(r'^django-admin/', admin.site.urls),
    # login / logout
    url(r'^login$', views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout$', views.LogoutView.as_view(next_page='/'), name='logout'),
    # permissions managment
    url(r'^', include('permissions.urls')),
    # account managment
    url(r'^', include('accounts.urls')),
    # tracker
    url(r'^', include('tracker.urls')),
]

tracker/urls.py
from django.conf.urls import url, include

from tracker import views, api


urlpatterns = [
    url(r'^markdown/$', views.markdown_preview, name='markdown'),
    # API
    url(r'^api/email/recv/$', api.email_recv, name='recv-email'),
    # Administration: redirect on first available admin page
    url(r'^admin/$', views.admin, name='admin'),
    # Settings
    url(r'^admin/settings/$', views.settings_list, name='settings'),
    # Projects
    url(r'^$', views.project_list, name='list-project'),
    url(r'^archived/$', views.project_list, {'archived': True}, name='list-archived-project'),
    url(r'^add/$', views.project_add, name='add-project'),
    url(r'^(?P<project>[-\w]+)/edit/$', views.project_edit, name='edit-project'),
    url(r'^(?P<project>[-\w]+)/delete/$', views.project_delete, name='delete-project'),
    url(r'^(?P<project>[-\w]+)/subscribe/$', views.project_subscribe, name='subscribe-project'),
    url(r'^(?P<project>[-\w]+)/unsubscribe/$', views.project_unsubscribe, name='unsubscribe-project'),
    url(r'^(?P<project>[-\w]+)/markread/$', views.project_mark_as_read, name='mark-read'),
    url(r'^(?P<project>[-\w]+)/archive/$', views.project_archive, {'archive': True}, name='archive-project'),
    url(r'^(?P<project>[-\w]+)/unarchive/$', views.project_archive, {'archive': False}, name='unarchive-project'),
    # Issues
    url(r'^(?P<project>[-\w]+)/issues/$', views.issue_list, name='list-issue'),
    url(r'^(?P<project>[-\w]+)/issues/add/$', views.issue_edit, name='add-issue'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/$', views.issue_details, name='show-issue'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/edit/$', views.issue_edit, name='edit-issue'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/delete/$', views.issue_delete, name='delete-issue'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/close/$', views.issue_close, name='close-issue'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/reopen/$', views.issue_reopen, name='reopen-issue'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/comment/$', views.issue_comment_edit, name='add-comment'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/comments/(?P<comment>[0-9]+)/edit/$', views.issue_comment_edit, name='edit-comment'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/comments/(?P<comment>[0-9]+)/delete/$', views.issue_comment_delete, name='delete-comment'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/subscribe/$', views.issue_subscribe, name='subscribe-issue'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/unsubscribe/$', views.issue_unsubscribe, name='unsubscribe-issue'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/add-label/(?P<label>[0-9]+)/$', views.issue_add_label, name='add-label-to-issue'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/remove-label/(?P<label>[0-9]+)/$', views.issue_remove_label, name='remove-label-from-issue'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/add-milestone/(?P<milestone>[a-z0-9_.-]+)/$', views.issue_add_milestone, name='add-milestone-to-issue'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/remove-milestone/(?P<milestone>[a-z0-9_.-]+)/$', views.issue_remove_milestone, name='remove-milestone-from-issue'),
    # Labels
    url(r'^(?P<project>[-\w]+)/labels/$', views.label_list, name='list-label'),
    url(r'^(?P<project>[-\w]+)/labels/add/$', views.label_edit, name='add-label'),
    url(r'^(?P<project>[-\w]+)/labels/(?P<id>[0-9]+)/edit/$', views.label_edit, name='edit-label'),
    url(r'^(?P<project>[-\w]+)/labels/(?P<id>[0-9]+)/delete/$', views.label_delete, name='delete-label'),
    # Milestones
    url(r'^(?P<project>[-\w]+)/milestones/$', views.milestone_list, name='list-milestone'),
    url(r'^(?P<project>[-\w]+)/milestones/add/$', views.milestone_edit, name='add-milestone'),
    url(r'^(?P<project>[-\w]+)/milestones/(?P<name>[a-z0-9_.-]+)/edit/$', views.milestone_edit, name='edit-milestone'),
    url(r'^(?P<project>[-\w]+)/milestones/(?P<name>[a-z0-9_.-]+)/close/$', views.milestone_close, name='close-milestone'),
    url(r'^(?P<project>[-\w]+)/milestones/(?P<name>[a-z0-9_.-]+)/reopen/$', views.milestone_reopen, name='reopen-milestone'),
    url(r'^(?P<project>[-\w]+)/milestones/(?P<name>[a-z0-9_.-]+)/delete/$', views.milestone_delete, name='delete-milestone'),
    # Activities
    url(r'^(?P<project>[-\w]+)/activity/$', views.activity, name='show-activity'),
    # Default redirection
    url(r'^(?P<project>[-\w]+)/$', views.project_redirect),
]

tracker/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.validators import RegexValidator
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.html import escape, format_html
from django.contrib.sites.models import Site
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ObjectDoesNotExist

from colorful.fields import RGBColorField

import json
from datetime import datetime, timedelta

from accounts.models import User


__all__ = ['Project', 'Issue', 'Label', 'Milestone', 'ReadState', 'Event']


class Settings(models.Model):

    EDIT_NOTIMEOUT = 0
    EDIT_TIMEOUT = 1
    EDIT_NOMORECOMMENT = 2
    EDIT_TYPE = (
        (EDIT_NOTIMEOUT, 'No timeout'),
        (EDIT_TIMEOUT, 'Timeout'),
        (EDIT_NOMORECOMMENT, 'As long no next comment'),
    )

    site = models.OneToOneField(Site, editable=False,
            related_name='settings', on_delete=models.CASCADE)
    items_per_page = models.IntegerField(default=25,
            verbose_name="Items per page",
            validators=[
                MinValueValidator(1),
                MaxValueValidator(500)
            ])
    edit_policy = models.IntegerField(choices=EDIT_TYPE,
            default=EDIT_NOTIMEOUT,
            verbose_name="Policy for \"Modify his issue and comment\" permission")
    edit_policy_timeout = models.IntegerField(default=30,
            verbose_name="Timeout for \"Modify his issue and comment\" permission (in min)",
            validators=[
                MinValueValidator(1),
            ])




class Project(models.Model):

    class Meta:
        ordering = ['name']

    ACCESS_PUBLIC = 1
    ACCESS_REGISTERED = 2
    ACCESS_PRIVATE = 3
    ACCESS_TYPE = (
        (ACCESS_PUBLIC, 'Public'),
        (ACCESS_REGISTERED, 'Registration required'),
        (ACCESS_PRIVATE, 'Private'),
    )

    display_name = models.CharField(max_length=32, unique=True,
            verbose_name="Project name")

    name = models.SlugField(max_length=32, unique=True,
            verbose_name="URL name")

    description = models.TextField(blank=True, default="",
            verbose_name="Description")

    access = models.IntegerField(choices=ACCESS_TYPE, default=ACCESS_PUBLIC)

    subscribers = models.ManyToManyField(User, blank=True,
            related_name='subscribed_projects')

    archived = models.BooleanField(default=False)

    @property
    def labels(self):
        return Label.objects.filter(project=self, deleted=False)

    @property
    def milestones(self):
        return Milestone.objects.filter(project=self, deleted=False)

    def get_unread_issues_nb(self, user):
        if not user.is_authenticated:
            return 0
        count = 0
        for issue in self.issues.all():
            if issue.have_unread_message(user):
                count +=1
        return count


    def __str__(self):
        return self.display_name


class Label(models.Model):

    project = models.ForeignKey(Project, related_name='+', on_delete=models.CASCADE)

    name = models.CharField(max_length=32)

    deleted = models.BooleanField(default=False)

    color = RGBColorField(default='#000000',
            verbose_name="Background color")

    inverted = models.BooleanField(default=True,
            verbose_name="Inverse text color")

    @property
    def url(self):

        url = reverse('list-issue', kwargs={'project': self.project.name})
        url += '?q=is:open%20label:' + self.quotted_name

        return mark_safe(url)

    @property
    def style(self):

        if self.inverted:
            fg = '#fff'
        else:
            fg = '#000'

        style = "background-color: {bg}; color: {fg}; vertical-align: middle;"

        return style.format(bg=self.color, fg=fg)

    @property
    def quotted_name(self):
        if ' ' in self.name:
            name = '&quot;' + escape(self.name) + '&quot'
        else:
            name = escape(self.name)
        return mark_safe(name)

    def __str__(self):
        return self.name


class Milestone(models.Model):

    class Meta:
        ordering = ['due_date']
        unique_together = ['project', 'name']

    name_validator = RegexValidator(regex='^[a-z0-9_.-]+$',
            message="Please enter only lowercase characters, number, "
                    "dot, underscores or hyphens.")

    project = models.ForeignKey(Project, related_name='+', on_delete=models.CASCADE)

    name = models.CharField(max_length=32, validators=[name_validator])

    due_date = models.DateTimeField(blank=True, null=True)

    closed = models.BooleanField(default=False)

    deleted = models.BooleanField(default=False)

    def closed_issues(self):

        return self.issues.filter(closed=True).count()

    def total_issues(self):

        return self.issues.count()

    def progress(self):

        closed = self.closed_issues()
        total = self.total_issues()

        if total:
            return int(100 * closed / total)
        else:
            return 0

    @property
    def url(self):

        url = reverse('list-issue', kwargs={'project': self.project.name})
        url += '?q=is:open%20milestone:' + self.name

        return mark_safe(url)

    def __str__(self):
        return self.name


class Issue(models.Model):

    # id is the id in the project, not the pk, so we need one
    primarykey = models.AutoField(primary_key=True)

    project = models.ForeignKey(Project, related_name='issues', on_delete=models.CASCADE)
    id = models.IntegerField(editable=False)

    class Meta:
        unique_together = ['project', 'id']

    title = models.CharField(max_length=128)

    author = models.ForeignKey(User, related_name='+', on_delete=models.PROTECT)

    opened_at = models.DateTimeField(auto_now_add=True)

    due_date = models.DateTimeField(blank=True, null=True)

    closed = models.BooleanField(default=False)

    labels = models.ManyToManyField(Label, blank=True,
            related_name='issues')

    milestone = models.ForeignKey(Milestone, blank=True, null=True,
            related_name='issues', on_delete=models.SET_NULL)

    assignee = models.ForeignKey(User, blank=True, null=True, related_name='+',
            on_delete=models.SET_NULL)

    subscribers = models.ManyToManyField(User, blank=True,
            related_name='subscribed_issues')

    @staticmethod
    def next_id(project):

        last_issue = project.issues.last()
        if last_issue:
            return last_issue.id + 1
        else:
            return 1

    @property
    def comments(self):

        return self.events.filter(code=Event.COMMENT)

    @property
    def overdue(self):

        if self.due_date:
            return self.due_date < timezone.now()
        else:
            return False

    def getdescevent(self):
        desc = self.events.filter(code=Event.DESCRIBE)
        if desc.exists():
            return desc.first()
        else:
            return None

    def getdesc(self):
        desc = self.getdescevent()
        if desc:
            return desc.additionnal_section
        else:
            return None

    def setdesc(self, value):
        desc = self.getdescevent()
        if desc:
            desc.additionnal_section = value
            desc.save()
        else:
            desc = Event(issue=self, author=self.author, code=Event.DESCRIBE,
                    additionnal_section=value)
            desc.save()

    def deldesc(self):
        desc = self.getdescevent()
        if desc:
            desc.delete()

    description = property(getdesc, setdesc, deldesc)

    def add_label(self, author, label, commit=True):
        if self.labels.filter(pk=label.pk).exists():
            return
        self.labels.add(label)
        if commit:
            self.save()
        event = Event(issue=self, author=author,
                code=Event.ADD_LABEL, args={'label': label.id})
        event.save()

    def remove_label(self, author, label, commit=True):
        self.labels.remove(label)
        if commit:
            self.save()
        event = Event(issue=self, author=author,
                code=Event.DEL_LABEL, args={'label': label.id})
        event.save()

    def add_milestone(self, author, milestone, commit=True):
        if self.milestone == milestone:
            return
        if self.milestone:
            event = Event(issue=self, author=author,
                    code=Event.CHANGE_MILESTONE,
                    args={'old_milestone': self.milestone.name,
                          'new_milestone': milestone.name})
            event.save()
        else:
            event = Event(issue=self, author=author,
                    code=Event.SET_MILESTONE,
                    args={'milestone': milestone.name})
            event.save()
        self.milestone = milestone
        if commit:
            self.save()

    def remove_milestone(self, author, milestone, commit=True):
        self.milestone = None
        if commit:
            self.save()
        event = Event(issue=self, author=author,
                code=Event.UNSET_MILESTONE,
                args={'milestone': milestone.name})
        event.save()

    def have_unread_message(self, user):
        if not user.is_authenticated:
            return False
        try:
            readstate = self.readstates.get(user=user)
        except ObjectDoesNotExist:
            return True
        return self.events.filter(date__gt=readstate.lastread).exists()

    def get_unread_event_nb(self, user):
        if not user.is_authenticated:
            return 0
        try:
            readstate = self.readstates.get(user=user)
        except ObjectDoesNotExist:
            return self.events.count()
        return self.events.filter(date__gt=readstate.lastread).count()

    def mark_as_read(self, user):

tracker/forms.py
from django import forms

from tracker.models import *
from tracker.models import Settings


__all__ = [
    'SettingsForm', 'ProjectForm', 'LabelForm', 'IssueForm', 'MilestoneForm', 'CommentForm'
]


class SettingsForm(forms.ModelForm):
    class Meta:
        model = Settings
        exclude = ('Site',)

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['display_name', 'name', 'description', 'access']
        help_texts = {
            'name': 'Warning: if you change this value, '
                    'this will break existing URLs.'
        }


class IssueForm(forms.ModelForm):
    class Meta:
        model = Issue
        fields = ['title', 'due_date']
    description = forms.CharField(widget=forms.Textarea, required=False)


class CommentForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea)


class LabelForm(forms.ModelForm):
    class Meta:
        model = Label
        fields = ['name', 'color', 'inverted']


class MilestoneForm(forms.ModelForm):
    class Meta:
        model = Milestone
        fields = ['name', 'due_date']

tracker/templates/tracker/activity.html
{% extends 'tracker/project_base.html' %}

{% load humanize %}
{% load bootstrap3 %}
{% load tracker_tags %}

{% block activitytab %}primary{% endblock %}

{% block tabcontent %}

{% if paginator.count %}
{% for event in events %}
<div class="panel panel-default">
  <div class="panel-heading">
    <span class="badge"><span class="glyphicon glyphicon-{{ event.glyphicon }}"></span></span>
    &#160;
    <a href="{% same_author event.author %}">{% user_badge event.author %}</a>
    {{ event.activity|safe }}
    <a href="{% url 'show-issue' project.name event.issue.id %}"><b data-original-title="" data-toggle="tooltip" data-placement="bottom" title="#{{ event.issue.id }}">{{ event.issue }}</b></a>
    {{ event.date|naturaltime }}
  </div>
</div>
{% endfor %}
{% else %}
<ul class="list-group">
  <li class="list-group-item">
    <em>There aren't any events for this project quite yet.</em>
  </li>
</ul>
{% endif %}

{% if events %}
<div style="text-align: center;">
    {% bootstrap_pagination events %}
</div>
{% endif %}

{% endblock %}

tracker/templates/tracker/comment_edit.html
{% extends 'tracker/issue_base.html' %}

{% load static %}

{% block tabcontent %}

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="page-header">
      <h1>
        {% if comment %}
        Edit comment
        {% else %}
        New comment
        {% endif %}
      </h1>
    </div>
    <form method="post" role="form">
      {% csrf_token %}
      <ul class="nav nav-tabs" role="tablist">
        <li class="active"><a href="#editor" role="tab" data-toggle="tab">Editor</a></li>
        <li><a href="#preview" role="tab" data-toggle="tab">Preview</a></li>
        <li><a href="https://daringfireball.net/projects/markdown/syntax" target="blank" role="tab">Syntax</a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="editor" style="max-height: 220px;">
          <div class="form-group">
            <textarea style="width: 100%; height: 220px;" id="markdown-content" data-project="{{ project.name }}" name="comment" required>{{ form.comment.value|default_if_none:"" }}</textarea>
          </div>
        </div>
        <div class="tab-pane well" id="preview" style="min-height: 200px; magin: 0;">
          <div id="preview-content"></div>
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-pencil"></span> Submit</button>
          <a href="{% url 'show-issue' project.name issue.id %}" class="btn btn-default">Cancel</a>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock %}

{% block js_end %}
{{ block.super }}
<script type="text/javascript">
var markdown_preview_url = "{% url 'markdown' %}";
</script>
<script src="{% static 'jquery.cookie/jquery.cookie.js' %}"></script>
<script src="{% static 'js/markdown-preview.js' %}"></script>
{% endblock %}

tracker/templates/tracker/issue_base.html
{% extends 'tracker/project_base.html' %}

{% block title %}{% if issue %}{{ issue }} - {% endif %}{{ project }} - PonyTracker{% endblock %}

{% block issuetab %}primary{% endblock %}

{% block rightbar %}
  {% if perm.create_issue %}
  <a href="{% url 'add-issue' project.name %}?prev={{ request.get_full_path }}" class="btn btn-success">New issue</a>
  {% endif %}
{% endblock %}

tracker/templates/tracker/label_edit.html
{% extends 'tracker/project_base.html' %}

{% load bootstrap3 %}

{% block labeltab %}primary{% endblock %}

{% block rightbar %}
  {% if label %}
  <a href="{% url 'add-label' project.name %}" class="btn btn-success">New label</a>
  {% endif %}
{% endblock %}

{% block tabcontent %}

<div class="row">
  <div class="col-md-offset-4 col-md-4">

    <div class="page-header">
      <h3>
        {% if label %}
        Edit label
        {% else %}
        New label
        {% endif %}
      </h3>
    </div>

    <form action="" method="post" role="form">
      {% bootstrap_form form %}
      {% csrf_token %}
      {% buttons %}
        <button type="submit" class="btn btn-primary">Submit</button>
        <a href="{{ cancel }}" class="btn btn-default">Cancel</a>
      {% endbuttons %}
    </form>
  </div>
</div>

{% endblock %}

tracker/templates/tracker/label_list.html
{% extends 'tracker/project_base.html' %}

{% load tracker_tags %}

{% block labeltab %}primary{% endblock %}

{% block rightbar %}
  {% if perm.manage_tags %}
  <a href="{% url 'add-label' project.name %}" class="btn btn-success">New label</a>
  {% endif %}
{% endblock %}

{% block tabcontent %}

<ul class="list-group">
  {% if labels.count %}
  {% for label in labels %}
  <li class="list-group-item">
      <a href="{{ label.url }}" class="btn" style="{{ label.style }}"><span class="glyphicon glyphicon-tag" style="font-size: 100%;"></span> {{ label }}</a>
      {% if perm.manage_tags or perm.delete_tags %}
      <div class="pull-right">
        {% if perm.manage_tags %}
        <a href="{% url 'edit-label' project.name label.id %}" class="btn btn-primary"><span class="glyphicon glyphicon-edit"></span> Edit</a>
        {% endif %}
        {% if perm.delete_tags %}
        <a href="#" data-item="label" data-action="{% url 'delete-label' project.name label.id %}" data-toggle="modal" data-target="#confirm-delete" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span> Delete</a>
        {% endif %}
      </div>
      {% endif %}
  </li>
  {% endfor %}
  {% else %}
  <li class="list-group-item">
    <em>There aren't any labels for this project quite yet.</em>
  </li>
  {% endif %}
</ul>

{% endblock %}

tracker/templates/tracker/milestone_edit.html
{% extends 'tracker/project_base.html' %}

{% load bootstrap3 %}
{% load static %}

{% block milestonetab %}primary{% endblock %}

{% block rightbar %}
  <div class="btn-group" role="group">
    <a href="{% url 'list-milestone' project.name %}?show=open" class="btn btn-default{% if show == 'open' %} active{% endif %}">Open</a>
    <a href="{% url 'list-milestone' project.name %}?show=close" class="btn btn-default{% if show == 'close' %} active{% endif %}">Closed</a>
    <a href="{% url 'list-milestone' project.name %}?show=all" class="btn btn-default{% if show == 'all' %} active{% endif %}">All</a>
  </div>
  {% if perm.manage_tags %}
  <a href="{% url 'add-milestone' project.name %}" class="btn btn-success">New milestone</a>
  {% endif %}
{% endblock %}

{% block tabcontent %}

<div class="row">
  <div class="col-md-offset-4 col-md-4">

    <div class="page-header">
      <h1>
        {% if milestone %}
        Edit milestone
        {% else %}
        New milestone
        {% endif %}
      </h1>
    </div>

    <form action="" method="post" role="form">
      {% csrf_token %}
      {% bootstrap_field form.name %}
      <div class="form-group has-success"><label class="control-label" for="id_due_date">Due date</label>
        <div class="input-group date" id="id_due_date_picker">
          <input class="form-control" id="id_due_date" name="due_date" placeholder="Due date" title="" type="text" value="{{ milestone.due_date|date:'Y-m-d H:i' }}" />
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
      </div>
      {% buttons %}
        <button type="submit" class="btn btn-primary">Submit</button>
        <a href="{{ cancel }}" class="btn btn-default">Cancel</a>
      {% endbuttons %}
    </form>

  </div>
</div>

{% endblock %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css' %}" />
{% endblock %}

{% block js_end %}
{{ block.super }}
<script src="{% static 'moment/min/moment.min.js' %}"></script>
<script src="{% static 'eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js' %}"></script>
<script>
$(function() {
    $("#id_due_date_picker").datetimepicker({
        "format": "YYYY-MM-DD HH:mm",
        "widgetPositioning": {
            "horizontal": "right",
            "vertical": "auto"
        },
        "showClear": true
    });
});
</script>
{% endblock %}

tracker/templates/tracker/milestone_list.html
{% extends 'tracker/project_base.html' %}

{% block milestonetab %}primary{% endblock %}

{% block rightbar %}
  <div class="btn-group" role="group">
    <a href="{% url 'list-milestone' project.name %}?show=open" class="btn btn-default{% if show == 'open' %} active{% endif %}">Open</a>
    <a href="{% url 'list-milestone' project.name %}?show=close" class="btn btn-default{% if show == 'close' %} active{% endif %}">Closed</a>
    <a href="{% url 'list-milestone' project.name %}?show=all" class="btn btn-default{% if show == 'all' %} active{% endif %}">All</a>
  </div>
  {% if perm.manage_tags %}
  <a href="{% url 'add-milestone' project.name %}" class="btn btn-success">New milestone</a>
  {% endif %}
{% endblock %}

{% block tabcontent %}

<ul class="list-group">
  {% if milestones.count %}
  {% for milestone in milestones %}
  <li class="list-group-item">
    <div class="pull-right">
      {% if perm.manage_tags %}
      {% if milestone.closed %}
      <a href="{% url 'reopen-milestone' project.name milestone.name %}"><button class="btn btn-info"><span class="glyphicon glyphicon-repeat"></span> Reopen</button></a>
      {% else %}
      <a href="{% url 'close-milestone' project.name milestone.name %}"><button class="btn btn-info"><span class="glyphicon glyphicon-ok-circle"></span> Close</button></a>
      {% endif %}
      <a href="{% url 'edit-milestone' project.name milestone.name %}"><button class="btn btn-primary"><span class="glyphicon glyphicon-edit"></span> Edit</button></a>
      {% endif %}
      {% if perm.delete_tags %}
      <a href="#" data-item="milestone" data-action="{% url 'delete-milestone' project.name milestone.name %}" data-toggle="modal" data-target="#confirm-delete" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span> Delete</a>
      {% endif %}
    </div>
    <b style="font-size: 200%;">
      <span class="glyphicon glyphicon-road"></span> <a href="{% url 'list-issue' project.name %}?q=is:open%20milestone:{{ milestone.name }}">{{ milestone }}</a>
    </b>
    &#160;
    <small>
      <span style="white-space: nowrap;"><span class="glyphicon glyphicon-calendar"></span> {% if milestone.due_date %}Due by {{ milestone.due_date }}{% else %}No due date{% endif %}</span>
    </small>
    <br /><br />
    <div class="progress">
      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="{{ milestone.progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ milestone.progress }}%;">
        {{ milestone.progress }}% complete
      </div>
    </div>
  </li>
  {% endfor %}
  {% else %}
  <li class="list-group-item">
    <em>There aren't any milestones matching your desired criteria.</em>
  </li>
  {% endif %}
</ul>

{% endblock %}

tracker/templates/tracker/project_add.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% block content %}

<div class="page-header">
  <h1>
    New project
  </h1>
</div>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="page-header">
      <form action="" method="post" role="form">
        {%bootstrap_form form %}
        {% csrf_token %}
        {% buttons %}
          <button type="submit" class="btn btn-primary">Submit</button>
          <a href="{% url 'list-project' %}" class="btn btn-default">Cancel</a>
        {% endbuttons %}
      </form>
    </div>
  </div>
</div>

{% endblock %}