permissions/urls.py
from django.conf.urls import url, include

from permissions import views


urlpatterns = [
    # Global permissions
    url(r'^admin/permissions/$', views.global_perm_list, name='list-global-permission'),
    url(r'^admin/permissions/add/$', views.global_perm_edit, name='add-global-permission'),
    url(r'^admin/permissions/(?P<id>[0-9]+)/edit/$', views.global_perm_edit, name='edit-global-permission'),
    url(r'^admin/permissions/(?P<id>[0-9]+)/delete/$', views.global_perm_delete, name='delete-global-permission'),
    url(r'^admin/permissions/(?P<id>[0-9]+)/toggle/(?P<perm>[a-z_]+)/$', views.global_perm_toggle, name='toggle-global-permission'),
    # Project permissions
    url(r'^(?P<project>[-\w]+)/permissions/$', views.project_perm_list, name='list-project-permission'),
    url(r'^(?P<project>[-\w]+)/permissions/add/$', views.project_perm_edit, name='add-project-permission'),
    url(r'^(?P<project>[-\w]+)/permissions/(?P<id>[0-9]+)/edit/$', views.project_perm_edit, name='edit-project-permission'),
    url(r'^(?P<project>[-\w]+)/permissions/(?P<id>[0-9]+)/delete/$', views.project_perm_delete, name='delete-project-permission'),
    url(r'^(?P<project>[-\w]+)/permissions/(?P<id>[0-9]+)/toggle/(?P<perm>[a-z_]+)/$', views.project_perm_toggle, name='toggle-project-permission'),
]

ponytracker/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views


urlpatterns = [
    # django admin
    url(r'^django-admin/', admin.site.urls),
    # login / logout
    url(r'^login$', views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout$', views.LogoutView.as_view(next_page='/'), name='logout'),
    # permissions managment
    url(r'^', include('permissions.urls')),
    # account managment
    url(r'^', include('accounts.urls')),
    # tracker
    url(r'^', include('tracker.urls')),
]

tracker/urls.py
from django.conf.urls import url, include

from tracker import views, api


urlpatterns = [
    url(r'^markdown/$', views.markdown_preview, name='markdown'),
    # API
    url(r'^api/email/recv/$', api.email_recv, name='recv-email'),
    # Administration: redirect on first available admin page
    url(r'^admin/$', views.admin, name='admin'),
    # Settings
    url(r'^admin/settings/$', views.settings_list, name='settings'),
    # Projects
    url(r'^$', views.project_list, name='list-project'),
    url(r'^archived/$', views.project_list, {'archived': True}, name='list-archived-project'),
    url(r'^add/$', views.project_add, name='add-project'),
    url(r'^(?P<project>[-\w]+)/edit/$', views.project_edit, name='edit-project'),
    url(r'^(?P<project>[-\w]+)/delete/$', views.project_delete, name='delete-project'),
    url(r'^(?P<project>[-\w]+)/subscribe/$', views.project_subscribe, name='subscribe-project'),
    url(r'^(?P<project>[-\w]+)/unsubscribe/$', views.project_unsubscribe, name='unsubscribe-project'),
    url(r'^(?P<project>[-\w]+)/markread/$', views.project_mark_as_read, name='mark-read'),
    url(r'^(?P<project>[-\w]+)/archive/$', views.project_archive, {'archive': True}, name='archive-project'),
    url(r'^(?P<project>[-\w]+)/unarchive/$', views.project_archive, {'archive': False}, name='unarchive-project'),
    # Issues
    url(r'^(?P<project>[-\w]+)/issues/$', views.issue_list, name='list-issue'),
    url(r'^(?P<project>[-\w]+)/issues/add/$', views.issue_edit, name='add-issue'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/$', views.issue_details, name='show-issue'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/edit/$', views.issue_edit, name='edit-issue'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/delete/$', views.issue_delete, name='delete-issue'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/close/$', views.issue_close, name='close-issue'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/reopen/$', views.issue_reopen, name='reopen-issue'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/comment/$', views.issue_comment_edit, name='add-comment'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/comments/(?P<comment>[0-9]+)/edit/$', views.issue_comment_edit, name='edit-comment'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/comments/(?P<comment>[0-9]+)/delete/$', views.issue_comment_delete, name='delete-comment'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/subscribe/$', views.issue_subscribe, name='subscribe-issue'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/unsubscribe/$', views.issue_unsubscribe, name='unsubscribe-issue'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/add-label/(?P<label>[0-9]+)/$', views.issue_add_label, name='add-label-to-issue'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/remove-label/(?P<label>[0-9]+)/$', views.issue_remove_label, name='remove-label-from-issue'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/add-milestone/(?P<milestone>[a-z0-9_.-]+)/$', views.issue_add_milestone, name='add-milestone-to-issue'),
    url(r'^(?P<project>[-\w]+)/issues/(?P<issue>[0-9]+)/remove-milestone/(?P<milestone>[a-z0-9_.-]+)/$', views.issue_remove_milestone, name='remove-milestone-from-issue'),
    # Labels
    url(r'^(?P<project>[-\w]+)/labels/$', views.label_list, name='list-label'),
    url(r'^(?P<project>[-\w]+)/labels/add/$', views.label_edit, name='add-label'),
    url(r'^(?P<project>[-\w]+)/labels/(?P<id>[0-9]+)/edit/$', views.label_edit, name='edit-label'),
    url(r'^(?P<project>[-\w]+)/labels/(?P<id>[0-9]+)/delete/$', views.label_delete, name='delete-label'),
    # Milestones
    url(r'^(?P<project>[-\w]+)/milestones/$', views.milestone_list, name='list-milestone'),
    url(r'^(?P<project>[-\w]+)/milestones/add/$', views.milestone_edit, name='add-milestone'),
    url(r'^(?P<project>[-\w]+)/milestones/(?P<name>[a-z0-9_.-]+)/edit/$', views.milestone_edit, name='edit-milestone'),
    url(r'^(?P<project>[-\w]+)/milestones/(?P<name>[a-z0-9_.-]+)/close/$', views.milestone_close, name='close-milestone'),
    url(r'^(?P<project>[-\w]+)/milestones/(?P<name>[a-z0-9_.-]+)/reopen/$', views.milestone_reopen, name='reopen-milestone'),
    url(r'^(?P<project>[-\w]+)/milestones/(?P<name>[a-z0-9_.-]+)/delete/$', views.milestone_delete, name='delete-milestone'),
    # Activities
    url(r'^(?P<project>[-\w]+)/activity/$', views.activity, name='show-activity'),
    # Default redirection
    url(r'^(?P<project>[-\w]+)/$', views.project_redirect),
]

permissions/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms.widgets import HiddenInput

from permissions.models import *
from permissions.models import PermissionModel
from accounts.models import *


__all__ = ['GlobalPermissionForm', 'ProjectPermissionForm']


class PermissionForm(forms.ModelForm):

    class Meta:
        abstract = True

    # The grantee_id is a hidden field.
    # The user complete the grantee_name field, and the validation
    # method will set the correct value is the grantee_id.
    grantee_name = forms.CharField(max_length=32)

    def clean(self):

        data = super(PermissionForm, self).clean()

        if 'grantee_name' not in data or 'grantee_type' not in data:
            # a field required error will be printed so we dont care
            return data

        name = data['grantee_name']

        if int(data['grantee_type']) == PermissionModel.GRANTEE_USER:
            grantees = User.objects.filter(username=name)
            if not grantees.exists():
                raise ValidationError("User '%s' does not exists." % name)
        elif int(data['grantee_type']) == PermissionModel.GRANTEE_GROUP:
            grantees = Group.objects.filter(name=name)
            if not grantees.exists():
                raise ValidationError("Group '%s' does not exists." % name)
        elif int(data['grantee_type']) == PermissionModel.GRANTEE_TEAM:
            grantees = Team.objects.filter(name=name)
            if not grantees.exists():
                raise ValidationError("Team '%s' does not exists." % name)
        else:
            # grantee_type is not in choice set, an error will be reported
            return data

        data['grantee_id'] = grantees.first().id

        return data


class GlobalPermissionForm(PermissionForm):

    class Meta:
        model = GlobalPermission
        fields = ['grantee_type', 'grantee_id']
        widgets = {
            'grantee_id': HiddenInput,
        }


class ProjectPermissionForm(PermissionForm):

    class Meta:
        model = ProjectPermission
        # project is required for the unicity check
        fields = ['project', 'grantee_type', 'grantee_id']
        widgets = {
            'project': HiddenInput,
            'grantee_id': HiddenInput,
        }

permissions/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods
from django.contrib import messages
from django.http import Http404, HttpResponse
from django.core.exceptions import PermissionDenied


from permissions.models import *
from permissions.forms import *
from permissions.decorators import project_perm_required


@project_perm_required('manage_global_permission')
def global_perm_list(request):
    return render(request, 'permissions/global_perm_list.html', {
        'permissions': GlobalPermission.objects.all(),
    })


@project_perm_required('manage_global_permission')
def global_perm_edit(request, id=None):
    if id:
        perm = get_object_or_404(GlobalPermission, id=id)
        form = GlobalPermissionForm(request.POST or None, instance=perm)
    else:
        perm = None
        form = GlobalPermissionForm(request.POST or None, initial={
            'grantee_id': 0,
        })
    if request.method == 'POST' and form.is_valid():
        form.save()
        if id:
            messages.success(request, 'Permission updated successfully.')
        else:
            messages.success(request, 'Permission added successfully.')
        return redirect('list-global-permission')
    name = request.POST.get('grantee_name')
    if not name:
        if perm:
            name = perm.grantee.__str__()
        else:
            name = ''
    return render(request, 'permissions/global_perm_edit.html', {
        'permission': perm,
        'form': form,
        'name': name,
    })


@require_http_methods(["POST"])
@project_perm_required('manage_global_permission')
def global_perm_delete(request, id):
    perm = get_object_or_404(GlobalPermission, id=id)
    perm.delete()
    messages.success(request, 'Permission deleted successfully.')
    return redirect('list-global-permission')


@project_perm_required('manage_global_permission')
def global_perm_toggle(request, id, perm):
    permission = get_object_or_404(GlobalPermission, id=id)
    if perm not in permission.all_perms:
        raise Http404
    state = not getattr(permission, perm)
    setattr(permission, perm, state)
    permission.save()
    return HttpResponse('1' if state else '0')


@project_perm_required('manage_project_permission')
def project_perm_list(request, project):
    return render(request, 'permissions/project_perm_list.html', {
        'project': project,
        'permissions': ProjectPermission.objects.filter(project=project).all(),
    })


@project_perm_required('manage_project_permission')
def project_perm_edit(request, project, id=None):
    if id:
        perm = get_object_or_404(ProjectPermission, project=project, id=id)
        form = ProjectPermissionForm(request.POST or None, instance=perm)
    else:
        perm = None
        form = ProjectPermissionForm(request.POST or None, initial={
            'project': project.id,
            'grantee_id': 0,
        })
    if request.method == 'POST' and form.is_valid():
        if not form.cleaned_data['project'] == project:
            raise PermissionDenied()
        form.save()
        if id:
            messages.success(request, 'Permission updated successfully.')
        else:
            messages.success(request, 'Permission added successfully.')
        return redirect('list-project-permission', project.name)
    name = request.POST.get('grantee_name')
    if not name:
        if perm:
            name = perm.grantee.__str__()
        else:
            name = ''
    return render(request, 'permissions/project_perm_edit.html', {
        'project': project,
        'permission': perm,
        'form': form,
        'name': name,
    })


@require_http_methods(["POST"])
@project_perm_required('manage_project_permission')
def project_perm_delete(request, project, id):
    perm = get_object_or_404(ProjectPermission, project=project, id=id)
    perm.delete()
    messages.success(request, 'Permission deleted successfully.')
    return redirect('list-project-permission', project.name)


@project_perm_required('manage_project_permission')
def project_perm_toggle(request, project, id, perm):
    permission = get_object_or_404(ProjectPermission, project=project, id=id)
    if perm not in permission.all_perms:
        raise Http404
    state = not getattr(permission, perm)
    setattr(permission, perm, state)
    permission.save()
    return HttpResponse('1' if state else '0')

permissions/templates/permissions/global_perm_edit.html
{% extends 'admin.html' %}

{% load permissions_filters %}
{% load bootstrap3 %}
{% load static %}

{% block permtab %}primary{% endblock %}

{% block moretabs %}
{% if permission %}
<a href="{% url 'add-global-permission' %}" class="btn btn-success">Add permission</a>
{% endif %}
{% endblock %}

{% block tabcontent %}

<div class="row">
  <div class="col-md-offset-4 col-md-4">


    <div class="page-header">
      <h1>
        {% if permission %}
        Edit permission
        {% else %}
        Add permission
        {% endif %}
      </h1>
    </div>

    <form method="post" role="form">
      {% csrf_token %}
      {% bootstrap_form_errors form %}
      {% bootstrap_field form.grantee_type %}
      {% bootstrap_field form.grantee_id %}
      <div class="form-group">
        <label class="control-label" for="id_grantee_name">Grantee name</label>
        <input class="form-control" id="id_grantee_name" maxlength="32" name="grantee_name" placeholder="Grantee name" required="required" title="" type="text" value="{{ name }}" />
      </div>
      <div class="form-group text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
        <a href="{% url 'list-global-permission' %}" class="btn btn-default">Cancel</a>
      </div>
    </form>

  </div>
</div>

{% endblock %}

{% block js_end %}
{{ block.super }}
<script src="{% static 'js/perm.js' %}"></script>
{% endblock %}

permissions/templates/permissions/global_perm_list.html
{% extends 'admin.html' %}

{% load permissions_filters %}
{% load static %}

{% block permtab %}primary{% endblock %}

{% block moretabs %}
<a href="{% url 'add-global-permission' %}" class="btn btn-success">Add permission</a>
{% endblock %}

{% block tabcontent %}

{% if permissions.count %}
<div class="panel-group" id="accordion">
{% for perm in permissions %}
<div class="panel panel-default">
  <div class="pannel panel-heading">
    <h4 class="panel-title">
      <a name="perm{{ perm.id }}" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ perm.id }}">
        {{ perm.type }} {{ perm.name }}
      </a>
      <div class="pull-right">
        <a href="{% url 'edit-global-permission' perm.id %}" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-edit"></span> edit</a>
        <a href="#perm{{ perm.id }}" data-item="permission" data-action="{% url 'delete-global-permission' perm.id %}" data-toggle="modal" data-target="#confirm-delete" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-trash"></span> delete</a>
      </div>
    </h4>
  </div>
  <div class="panel-collapse collapse" id="collapse{{ perm.id }}">
    <div class="panel-body">
      <ul class="nav nav-tabs" role="tablist">
        <li class="active"><a href="#global{{ perm.id }}" role="tab" data-toggle="tab">On PonyTracker</a></li>
        <li><a href="#project{{ perm.id }}" role="tab" data-toggle="tab">On all projects</a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="global{{ perm.id }}">
          <ul class="list-group">
            {% for field, value in perm.global_perms_fields_values %}
            <li class="list-group-item">
              {{ field.verbose_name }}
              <a href="javascript:void(0);" class="pull-right perm-toggle" data-href="{% url 'toggle-global-permission' perm.id field.name %}">{{ value|boolean }}</a>
            </li>
            {% endfor %}
          </ul>
        </div>
        <div class="tab-pane" id="project{{ perm.id }}">
          <ul class="list-group">
            {% for field, value in perm.project_perms_fields_values %}
            <li class="list-group-item">
              {{ field.verbose_name }}
              <a href="javascript:void(0);" class="pull-right perm-toggle" data-href="{% url 'toggle-global-permission' perm.id field.name %}">{{ value|boolean }}</a>
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
{% endfor %}
</div>
{% else %}
<div class="well">
  No permissions defined yet.
</div>
{% endif %}

{% endblock %}

{% block js_end %}
{{ block.super }}
<script src="{% static 'js/perm.js' %}"></script>
{% endblock %}

permissions/templates/permissions/project_perm_edit.html
{% extends 'tracker/project_base.html' %}

{% load permissions_filters %}
{% load bootstrap3 %}
{% load static %}

{% block settingdropdownclass %} active{% endblock %}
{% block settingdropdown %}Permissions{% endblock %}

{% block tabcontent %}

<div class="row">
  <div class="col-md-offset-4 col-md-4">


    <div class="page-header">
      <h1>
        {% if permission %}
        Edit permission
        {% else %}
        Add permission
        {% endif %}
      </h1>
    </div>

    <form method="post" role="form">
      {% csrf_token %}
      {% bootstrap_form_errors form %}
      {% bootstrap_field form.project %}
      {% bootstrap_field form.grantee_type %}
      {% bootstrap_field form.grantee_id %}
      <div class="form-group">
        <label class="control-label" for="id_grantee_name">Grantee name</label>
        <input class="form-control" id="id_grantee_name" maxlength="32" name="grantee_name" placeholder="Grantee name" required="required" title="" type="text" value="{{ name }}" />
      </div>
      <div class="form-group text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
        <a href="{% url 'list-project-permission' project.name %}" class="btn btn-default">Cancel</a>
      </div>
    </form>

  </div>
</div>

{% endblock %}

{% block js_end %}
{{ block.super }}
<script src="{% static 'js/perm.js' %}"></script>
{% endblock %}

permissions/templates/permissions/project_perm_list.html
{% extends 'tracker/project_base.html' %}

{% load permissions_filters %}
{% load static %}

{% block settingdropdownclass %} active{% endblock %}
{% block settingdropdown %}Permissions{% endblock %}

{% block rightbar %}
<a href="{% url 'add-project-permission' project.name %}" class="btn btn-success">Add permission</a>
{% endblock %}

{% block tabcontent %}

{% if permissions.count %}
<div class="panel-group" id="accordion">
{% for perm in permissions %}
<div class="panel panel-default">
  <div class="pannel panel-heading">
    <h4 class="panel-title">
      <a name="perm{{ perm.id }}" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ perm.id }}">
        {{ perm.type }} {{ perm.name }}
      </a>
      <div class="pull-right">
        <a href="{% url 'edit-project-permission' project.name perm.id %}" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-edit"></span> edit</a>
        <a href="#perm{{ perm.id }}" data-item="permission" data-action="{% url 'delete-project-permission' project.name perm.id %}" data-toggle="modal" data-target="#confirm-delete" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-trash"></span> delete</a>
      </div>
    </h4>
  </div>
  <div class="panel-collapse collapse" id="collapse{{ perm.id }}">
    <div class="panel-body">
      <ul class="list-group">
        {% for field, value in perm.all_perms_fields_values %}
        <li class="list-group-item">
          {{ field.verbose_name }}
          <a href="javascript:void(0);" class="pull-right perm-toggle" data-href="{% url 'toggle-project-permission' project.name perm.id field.name %}">{{ value|boolean }}</a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endfor %}
</div>
{% else %}
<div class="well">
  No permissions defined yet.
</div>
{% endif %}

{% endblock %}

{% block js_end %}
{{ block.super }}
<script src="{% static 'js/perm.js' %}"></script>
{% endblock %}